### ISSUE TITLE
Is it possible to adapt it so that it passes form values to the variables sagepay needs.

### ISSUE THREAD

**Issue by con322** [tolzhabayev/sagepayForm-php#10]
So the user enters billing details and amount they wish to pay then this is sent to sagepay?

Would I just need to adapt the sagepay.php file so that the variables equal the post value of the field.

Or can I do this in the index.php where the form is. As the information would be set when the page loads but rather when the form is posted.

Not looking for a copy and paste answer just a point in the right direction.

**Comment by sumandey121** [comment]
mcrypt_encrypt Key of size 19 not supported by this algorithm..Please  help me

**Comment by tolzhabayev** [comment]
You should use key size of 16, why do you want to use 19?

**Comment by sumandey121** [comment]
how to do that?

**Comment by tolzhabayev** [comment]
if you use this library as is, it's already done. How do you integrate it and where does excatly the error comes from? Line Nr.?

**Comment by sumandey121** [comment]
<b>Warning</b>:  mcrypt_encrypt(): Key of size 19 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported in <b>C:\xampp\htdocs\sagepayForm-php-master\lib\SagePay.php</b> on line <b>543</b><br />

**Comment by tolzhabayev** [comment]
Show me the line 542 and 543 from your C:\xampp\htdocs\sagepayForm-php-master\lib\SagePay.php

**Comment by sumandey121** [comment]
protected function encryptAndEncode($strIn) {
		$strIn = $this->pkcs5_pad($strIn, 24);
		return "@".bin2hex(mcrypt_encrypt(MCRYPT_RIJNDAEL_128, $this->encryptPassword, $strIn, MCRYPT_MODE_CBC, $this->encryptPassword));
	}

**Comment by tolzhabayev** [comment]
$strIn = $this->pkcs5_pad($strIn, 16); says 16 so it cant be 19. Try changing the value and see if the error message gets different.

**Comment by sumandey121** [comment]
i tried to test by putting different values there, but same error message

**Comment by tolzhabayev** [comment]
then i dont really know how to help you

**Comment by sumandey121** [comment]
Its works Thanks

**Comment by tolzhabayev** [comment]
so what was the problem?
