### ISSUE TITLE
Status: 	INVALID  Status AND Detail: 5068 : The encryption method is not supported by this protocol version.

### ISSUE THREAD

**Issue by priyaranjan132** [tolzhabayev/sagepayForm-php#11]
I am using your code and always i am getting the same issue:

Status: 	INVALID
Status Detail: 	5068 : The encryption method is not supported by this protocol version.
Can you pls tell me where is the problem??
I think anything wrong in the encryption password.
How can encrypt my password?

**Comment by tolzhabayev** [comment]
Do you encrypt it using AES/CBC/PCKS#5 algorithm? Can you show some more of your code?

**Comment by JamesBarnsley** [comment]
Hi,
I am also having this problem.
I have set everything up using the class, and I am using the getCrypt() method to retrieve the end crypt result and I am getting the same error.
James.

**Comment by JamesBarnsley** [comment]
Problem was caused by the password I choose for the encrypt.

**Comment by DanaPDC** [comment]
Thanks a lot, it worked!

**Comment by tolzhabayev** [comment]
:+1:
