### ISSUE TITLE
Status Detail:	3045 : The Currency field is missing.

### ISSUE THREAD

**Issue by swindonwebdesign** [tolzhabayev/sagepayForm-php#15]
Despite adding $sagePay->setCurrency('GBP'); I get the following error: Status Detail: 3045 : The Currency field is missing. This currency is also set as GBP in the Sage control panel. Can you clarify?

**Comment by tolzhabayev** [comment]
It may have nothing to do with currency Field (it is strange, i know ) - it could be a problem with encrypting your whole data -> see http://stackoverflow.com/a/20728182/508803

So check your currency settings in control panel (test and live) and check the way you encrypt (getCrypt() in my class). Maybe you have some libraries missing at your host

**Comment by swindonwebdesign** [comment]
Hi, just got it working, as soon as I set my encryption password, worked straight away!

Much appreciated!
