### ISSUE TITLE
5005 error

### ISSUE THREAD

**Issue by andyc209** [tolzhabayev/sagepayForm-php#16]
i have downloaded these files and added my encryption password to sagepay.php and also added my values to the vendor name within the form and the vendortxtcode etc. When i process the form i get a 5005 error - do i need to install Sage's integration kit for PHP or does this replace their kit - am i missing something? Sorry, new to this :(

**Comment by tolzhabayev** [comment]
As you can see here: http://www.sagepay.co.uk/support/error-codes/5005-invalid-vendor-configuration-missing-or-invalid

it looks like your vendor account has not (yet?) been added to sagepay Test or Live plattform. Conctact the sage pay support team and ask how long will it take to setup your account.

**Comment by andyc209** [comment]
i do have an account - they had set my encryption password to Live rather than Test - got it reset.
Even though i changed it i am still getting the error - does this code work standalone without the need for their integration kit they have on their website?

**Comment by tolzhabayev** [comment]
Yes it works standalone. Integration Kit is an alternative way to integrate sagepay

**Comment by andyc209** [comment]
excellent - thankyou for your help
