### ISSUE TITLE
5080 Error

### ISSUE THREAD

**Issue by rickcj** [tolzhabayev/sagepayForm-php#20]
Hi,

I have been using this for our eBay customers to pay by card successfully for several months.

I have just gone to send a customer a link and thought I check it's still working as expected, but got the error:
5080 : Form transaction registration failed.

I tried to use your default index.php code and just checked the vendor, but got the same error?

I have tried setting it to use the test and live urls, but keep getting this same error.

I will contact SagePay to see if anything has changed and if they can help troubleshoot, but thought I would raise it here as well.

Grateful for any help you can provide.

Chris

**Comment by rickcj** [comment]
Spoke to SagePay support and they guided me to the MySagePay portal where you can view Invalid transactions to be able to troubleshoot this error.

It turned out I was using an old copy of our url with name instead of separate first name and last name!

Chris

**Comment by tolzhabayev** [comment]
glad you could sort this out 👍
