### ISSUE TITLE
Status: MALFORMED  Status Detail: 3045 : The Currency field is missing.

### ISSUE THREAD

**Issue by ScottGoMedia** [tolzhabayev/sagepayForm-php#7]
Hi there,

I keep getting the error mentioned above, I am pretty sure that everything is in place and don't know where I am going wrong.

Any chance you could have a look?

Thanks,

$sagePay = new SagePay();
$sagePay->setCurrency('GBP');
$sagePay->setAmount('100');
$sagePay->setDescription('Breakdown Cover');
$sagePay->setBillingSurname('Bowers');
$sagePay->setBillingFirstnames('Scott');
$sagePay->setBillingCity('Wakefield');
$sagePay->setBillingPostCode('WF59TJ');
$sagePay->setBillingAddress1('1 The Gateway, Fryersway');
$sagePay->setBillingCountry('gb');  
$sagePay->setDeliverySameAsBilling();

$sagePay->setSuccessURL($websiteRoot.'quote/step/6/success');
$sagePay->setFailureURL($websiteRoot.'quote/step/6/failure');

?>

<form method="POST" id="SagePayForm" action="https://test.sagepay.com/gateway/service/vspform-register.vsp">
  <input type="hidden" name="VPSProtocol" value= "3.00">
  <input type="hidden" name="TxType" value= "PAYMENT">
  <input type="hidden" name="Vendor" value= "VENDOR ID IS HERE">
  <input type="hidden" name="Crypt" value= "<?= $sagePay->getCrypt(); ?>">
  <input type="submit" value="continue to SagePay">
</form>

**Comment by feridmovsumov** [comment]
Reason of problem can be wrong encryption password. You should get yours from your  admin https://test.sagepay.com/mysagepay/settings.msp
