### ISSUE TITLE
Success Page Blank

### ISSUE THREAD

**Issue by mrtom100** [tolzhabayev/sagepayForm-php#9]
I have used this form and works great up until the success page.. I am getting a blank page i did a little test and it seems to not be able to pull or see that there is a encrypted content being sent via the url. I added a if else to check this and it is not pulling or seeing a value there so is not triggering the decode function..

Any help be great

**Comment by AndrewPaget** [comment]
I am also having the same problem in that the return url is too long. Please may I ask you if you have a resolve for this to view?

Thank you in advance.

**Comment by webbersky** [comment]
What is your problem exactly?

**Comment by AndrewPaget** [comment]
There are no buyers or shipping details passed back to success page

**Comment by webbersky** [comment]
Yes I found that also, I didn't ever use sagepay as we changed merchant in
the end, but maybe you could give sagepay a ring and ask them if it is
possible.
Or take a look at this document -
http://www.sagepay.co.uk/file/12246/download-document/SERVER_Integration_and_Protocol_Guidelines_010814.pdf

**Comment by MustardMike** [comment]
I've used the form and sent a successful transaction to the Test Server but my return url page success.php is giving me the following error Fatal error: Call to a member function decode() on a non-object in. The crypt parameter in the url contains 385 characters. Any ideas to what is causing this error.

**Comment by Tribal-Coder** [comment]
If you still face the problem - 
In success page, 

if ($_REQUEST['crypt']) {
	$responseArray = $sagePay->decode($_REQUEST['crypt']);

change to

if ($_REQUEST['crypt']) {
	$sagePay = new SagePay();
	$responseArray = $sagePay->decode($_REQUEST['crypt']);

That will make it work.

**Comment by MustardMike** [comment]
I updated PHP from 5.3.3 to 5.4 and works perfectly.
